# Generated by Django 2.0.6 on 2021-09-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferre', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['codigo'], 'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.AlterModelOptions(
            name='sell',
            options={'ordering': ['date_buy'], 'verbose_name': 'sell', 'verbose_name_plural': 'sells'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['amount'], 'verbose_name': 'stock', 'verbose_name_plural': 'stocks'},
        ),
        migrations.AlterField(
            model_name='producto',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
